x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

x-cpu-config:
  &cpu-config
  environment:
    - DISPLAY=${DISPLAY:?err}
    - LIBGL_ALWAYS_SOFTWARE=1

# new
volumes:
  plugin_ws_install:
    external: true

services:

  rosbot:
    image: ${SIMULATION_DOCKER_IMAGE:-husarion/rosbot-xl-gazebo:humble-0.9.1-20240131}
    <<: *gpu-config # or *cpu-config
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: ${SIMULATION_COMMAND:-ros2 launch rosbot_xl_gazebo simulation.launch.py mecanum:=${MECANUM:-True}}

  navigation:
    image: husarion/navigation2:humble-1.1.12-20240123

    # 2) Mount your Nav2 params and maps as before
    volumes:
      - ./config/nav2_${CONTROLLER:-rpp}_params.yaml:/params.yaml
      - ./maps:/maps

      # 3) Mount the plugin install-space (read‑only)
      - plugin_ws_install:/opt/ros/humble_plugin_ws:ro

    environment:
      - SAVE_MAP_PERIOD=${SAVE_MAP_PERIOD}

    # 4) Source the plugin workspace *first*, then Nav2’s install, then launch
    command:
      - bash
      - -lc
      - |
        source /opt/ros/humble/setup.bash && 
        source /opt/ros/humble_plugin_ws/setup.bash && \
        exec ros2 launch nav2_bringup bringup_launch.py \
          slam:=${SLAM:-True} \
          params_file:=/params.yaml \
          map:=/maps/map.yaml \
          use_sim_time:=True

  foxglove:
    image: husarion/foxglove:1.84.0
    ports:
      - 8080:8080
      - 8765:8765
    volumes:
      - ./config/layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - DS_HOST=foxglove-ds
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false

  foxglove-ds:
    image: husarion/foxglove-bridge:humble-0.7.3-20240108
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 capabilities:=[clientPublish,connectionGraph,assets]
