version: "3.8"

volumes:
  plugin_ws_install:

services:
  plugin_builder:
    build:
      context: .
      dockerfile: Dockerfile.build
      target: builder
      network: host
    volumes:
      - plugin_ws_install:/opt/ros/humble_plugin_ws:rw
    entrypoint: ["/bin/bash", "-lc", "exit 0"]
