# Dockerfile.build
FROM osrf/ros:humble-desktop AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      python3-colcon-common-extensions \
      ros-humble-navigation2 \
      ros-humble-nav2-core \
      ros-humble-nav2-costmap-2d \
      ros-humble-tf2-ros \
      ros-humble-pluginlib \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    python3-ament-package \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
# Copy entire repo (plugin code) into /workspace
COPY . /workspace
SHELL ["/bin/bash", "-lc"]

# Source ROS 2, then build with merged install layout
RUN source /opt/ros/humble/setup.bash && \
    colcon build \
      --merge-install \
      --install-base /opt/ros/humble_plugin_ws
